# Generated by Django 4.2.28 on 2026-02-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_herobanner_popup'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='text_overlays',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
