# Generated by Django 4.2.28 on 2026-02-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_herobanner_text_overlays'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('header', 'Header'), ('footer_nav', 'Footer Navigate'), ('footer_account', 'Footer Account')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=300)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('open_new_tab', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['location', 'display_order'],
            },
        ),
    ]
