# Generated by Django 4.2.28 on 2026-02-10 14:04

from django.db import migrations


def seed_menu_items(apps, schema_editor):
    MenuItem = apps.get_model('shop', 'MenuItem')
    if MenuItem.objects.exists():
        return

    items = [
        # Header
        ('header', 'Home', '/', 0),
        ('header', 'Shop', '/shop/', 1),
        ('header', 'Journal', '/blog/', 2),
        # Footer Navigate
        ('footer_nav', 'Home', '/', 0),
        ('footer_nav', 'Shop', '/shop/', 1),
        ('footer_nav', 'Journal', '/blog/', 2),
    ]
    for location, label, url, order in items:
        MenuItem.objects.create(
            location=location,
            label=label,
            url=url,
            display_order=order,
            is_active=True,
            open_new_tab=False,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_add_menuitem'),
    ]

    operations = [
        migrations.RunPython(seed_menu_items, migrations.RunPython.noop),
    ]
