# Generated by Django 4.2.28 on 2026-02-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_seed_menu_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Atelier des Poupées', max_length=200)),
                ('site_tagline', models.CharField(default='Sewn with devotion, worn with grace.', max_length=300)),
                ('site_description', models.TextField(default='Handcrafted doll garments inspired by centuries of textile artistry. Each piece tells a story woven with care and devotion.')),
                ('copyright_text', models.CharField(default='Atelier des Poupées', max_length=200)),
                ('color_parchment', models.CharField(default='#FFF3CD', max_length=7)),
                ('color_charcoal', models.CharField(default='#2D2926', max_length=7)),
                ('color_gold', models.CharField(default='#D4AF37', max_length=7)),
                ('color_velvet', models.CharField(default='#8B0000', max_length=7)),
                ('color_leather', models.CharField(default='#8B4513', max_length=7)),
                ('color_leather_light', models.CharField(default='#A0522D', max_length=7)),
            ],
            options={
                'verbose_name': 'Site Setting',
            },
        ),
    ]
